implemented hashSet
Alexsizoff7/java-collections-set pull request #1
Opened 2022-09-15 13:54 UTC by Alexsizoff7

2022-09-15 14:49 UTC, evgheni-panenco requested changes

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    private List <LinkedList<Student>> buckets;
Unnecessary space between variable type and diamond operator.

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    private static final int DEFAULT_CAPACITY = 16;
It's better to define your constants at the top of your class.

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    public StudentSet (int capacity) {
Unnecessary space between constructor name and parameter list

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            }
Wrong code format (indentation)

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        // counter < ts.len-1 then ts[counter+1, ..., len-1] = null
I think you could remove this comment

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    void resizeCheck () {
Access modifier is absent

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        buckets = new ArrayList <>(capacity);
Same with extra space. Hint - you could use in-built formatter in IDEA, for that select the code that is needed to be formatter (or the whole file) and press ctrl + alt + L.

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        if (o instanceof Student) {
Nothing needed to be changed, just FYI in case you're using java version > 14, you could use the following feature - https://www.baeldung.com/java-pattern-matching-instanceof

Since we are using a dino, it's ok)

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
>      public boolean add(Student student) {
1. Passing null to the method will cause NullPointerException
2. Also please note that original HashSet allow to store single null.
![image](https://user-images.githubusercontent.com/65505271/190432926-35fd0439-f224-4316-813e-b8c721cba026.png)


Also keep in mind that methods contains and remove should also work as the original collection.

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
>      public boolean remove(Object o) {
check comment for add() method

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        // toArray() and store its result
comments could be deleted

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        Object [] elements;
In order to avoid casting in next() method we could use toArray(T[] ts) method and store array of Students

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            size = size();
Variable size could be accessed from the outer class, so probably we don't need this extra variable in inner class.

2022-09-15 14:49 UTC, evgheni-panenco commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            nextStudent = (Student) elements[elementIndex];
Could be combined as single statement `return elements[elementIndex];`

2022-09-19 07:41 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    private List <LinkedList<Student>> buckets;
Fixed

2022-09-19 07:41 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    private static final int DEFAULT_CAPACITY = 16;
Fixed

2022-09-19 07:41 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    public StudentSet (int capacity) {
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            }
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        // counter < ts.len-1 then ts[counter+1, ..., len-1] = null
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +    void resizeCheck () {
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        buckets = new ArrayList <>(capacity);
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        if (o instanceof Student) {
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
>      public boolean add(Student student) {
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
>      public boolean remove(Object o) {
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        // toArray() and store its result
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +        Object [] elements;
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            size = size();
Fixed

2022-09-19 07:42 UTC, Alexsizoff7 commented on src/main/java/com/endava/internship/collections/StudentSet.java
> +            nextStudent = (Student) elements[elementIndex];
Fixed

2022-09-19 07:51 UTC, evgheni-panenco approved these changes

2022-09-19 12:34 UTC, merged